CREATE TABLE DENUNCIA(
	COD_DENUNCIA INT(11) PRIMARY KEY,
	DENUNCIA_MOTIVO VARCHAR(40),
	DENUNCIA_NOMBRE VARCHAR(15),
	DENUNCIA_APELLIDOS VARCHAR(30),
	DENUNCIA_CARRERA VARCHAR(30),
	DENUNCIA_DESCRIPCION_FISICA VARCHAR(300),
	DENUNCIA_CONTEXTO VARCHAR(300),
	DENUNCIA_DETALLE VARCHAR(300),
	DENUNCIA_INFORME VARCHAR(100),
	DENUNCIA_ESTADO VARCHAR(10));

CREATE TABLE USUARIO(
	USUARIO_RUT VARCHAR(12) PRIMARY KEY,
	USUARIO_TIPO VARCHAR(40),
	USUARIO_NOMBRE VARCHAR(20),
	USUARIO_APELLIDOS VARCHAR(60),
	USUARIO_CARRERA VARCHAR(30),
	USUARIO_ESTADO VARCHAR(10));

CREATE TABLE NOMBRAR_EQUIPO(
	COD_DENUNCIA INT(11),
	USUARIO_RUT VARCHAR(12),
	FOREIGN KEY(COD_DENUNCIA) REFERENCES DENUNCIA(COD_DENUNCIA),
	FOREIGN KEY(USUARIO_RUT) REFERENCES USUARIO(USUARIO_RUT));	

ALTER TABLE `NOMBRAR_EQUIPO` ADD FOREIGN KEY (`COD_DENUNCIA`) REFERENCES `DENUNCIA`(`COD_DENUNCIA`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `NOMBRAR_EQUIPO` ADD FOREIGN KEY (`USUARIO_RUT`) REFERENCES `USUARIO`(`USUARIO_RUT`) ON DELETE RESTRICT ON UPDATE CASCADE;
